langchain4j:
  open-ai:
    chat-model:
      api-key: ${API-KEY}
      model-name: deepseek-reasoner
      base-url: https://api.deepseek.com/v1
      log-requests: true
      log-responses: true


    streaming-chat-model:
      base-url: https://api.deepseek.com/v1
      api-key: ${API-KEY}
      model-name: deepseek-reasoner
      log-requests: true
      log-responses: true

    embedding-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${Ali-API-KEY}
      model-name: text-embedding-v3
      log-requests: true
      log-responses: true
      max-segments-per-batch: 10

spring:
  cache:
    redis:
      host: localhost
      port: 6379


